development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: web_asean_development
  host: localhost
  pool: 5
  username: myapp
  password: 1234

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: web_asean_test
  host:     localhost
  pool: 5
  username: myapp
  password: 1234

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: web_asean_production
  host:     localhost
  pool: 5
  username: myapp
  password: 1234
